parameters:
#    shop_bookshop.example.class: Shop\BookshopBundle\Example
    finder.class: Symfony\Component\Finder\Finder

services:
#    shop_bookshop.example:
#        class: %shop_bookshop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    finder:
        class: "%finder.class%"
#    